feat: add Herbarium to create REST endpoints
herbsjs/herbs2rest pull request #25
Opened 2022-03-16 23:21 UTC by rikdprogramador

Routes were created using custom files and repetitive writing. With this feature, there will be a
faster alternative to do this same route path as herbs2rest will use herbarium to generate the
endpoints. In addition, a test code was implemented to validate this function.

Fixes [#22](https://github.com/herbsjs/herbs2rest/issues/22)

## Readiness Checklist

### Author/Contributor
- [X] If documentation is needed for this change, has that been included in this pull request
- [ ] Remember to check if code coverage decrease, if so, please implement the necessary tests

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

2022-03-17 12:03 UTC, italojs requested changes

2022-03-17 12:03 UTC, italojs commented on src/generateRoutesWithHerbarium.js
> +    const items = Array.from(herbarium.usecases.all.values()).map(e => ({ id: e.entity, group: e.group }))
could you use explicit name declaration in `e` variable?
following the clean code, in this way we could to build a easy code to read

2022-03-21 17:35 UTC, italojs commented
before we merge it, could you add an herbrarium session into https://herbsjs.org/docs/glues/herbs2rest, please?

2022-03-21 19:02 UTC, italojs commented
great https://github.com/herbsjs/herbsjs.github.io/pull/117

2022-03-21 23:36 UTC, italojsv commented
@dalssoft  @jhomarolo some one could to merge it?

2022-03-22 14:53 UTC, dalssoft commented
I need to do make a deeper review for this PR but I haven't got the time. The way it is now it does not support simple cases, like overriding a route (which would be possible if the file for conversion was on the project, not in the lib).

2022-03-30 13:06 UTC, maikvortx commented
@dalssoft What do you think about sending new PRs with new functionality like your example? This PR is just the beginning of the functionality with its basic purpose.

2022-04-14 10:25 UTC, italojs approved these changes

2022-04-14 15:46 UTC, jhomarolo commented
@italojs it seems that @dalssoft requested some changes in his last comment

2022-04-16 18:39 UTC, dalssoft commented
What if instead of giving `generateRoutesWithHebarium` to the developer (a function with (1) to many responsibilities and (2) ugly name) we just expose a new `getControllers`:

The developer would need to do just that on the application side:

```js
const { getControllers , generateRoutes } = require('@herbsjs/herbs2rest')

const controllers = getControllers(herbarium)
... // opportunity to change controllers object if needed
generateRoutes(controllers, routes, showEndpoints)
``` 

This also would give the oportunity to change the returned controllers object if needed.

2022-04-16 18:43 UTC, dalssoft requested changes

2022-04-16 18:43 UTC, dalssoft commented on package.json
> +  "dependencies": {
It seems that `"@herbsjs/herbarium"` should be a `peerDependencies`, right?

2022-05-04 23:58 UTC, italojs commented
I dont agree the idea the herbrarium is a peer dependency as this lib still is in beta, we will change it a lot and the herbs2rest will need to be compatible with the developer herbrarium version, I'm not sure if this is a good idea

2022-05-05 11:51 UTC, dalssoft commented
> herbs2rest will need to be compatible with the developer herbrarium version

since this feature is focused on creating a link between herbrarium and herbs2rest, I don't see how this can be accomplish it without the dependency

2022-05-05 13:06 UTC, italojs commented
if we use it as a dependecy instead peerDependeecy when someone install the herbs2rest, the correct version for herbs2rest will be installed, so if the developer would like to install the herbrarium with a different version to use it in they project, they could to do it

2022-05-05 21:47 UTC, dalssoft commented
> if we use it as a dependecy instead peerDependeecy when someone install the herbs2rest, the correct version for herbs2rest will be installed, so if the developer would like to install the herbrarium with a different version to use it in they project, they could to do it

however the herbrarium object instance passed to herbs2rest function will always be the one from the developer project, not from the herbs2rest, so herbs2rest will use the "host" version anyways

2022-05-13 17:26 UTC, italojs commented
make sense

2022-06-07 18:20 UTC, jhomarolo commented
@rikdprogramador do you still here in this PR?

2022-06-10 12:31 UTC, dalssoft commented
Pls, check this comment: https://github.com/herbsjs/herbs2rest/pull/25#issuecomment-1100728874

2022-06-10 17:05 UTC, rikdprogramador commented
I am working on it!

2022-08-16 15:09 UTC, jhomarolo commented
This pr was resolved with #35

2022-08-16 15:09 UTC, closed without merging