feat: application crashes when property entity is not passed
herbsjs/herbs2rest pull request #34
Opened 2022-06-28 23:20 UTC by mtperesvx

- Update documentation with this new feature.
- Fix application crashes when property entity  is not passed in generateRoutes

2022-06-29 12:38 UTC, jhomarolo requested changes

2022-06-29 12:38 UTC, jhomarolo commented on test/generateRoutes.test.js
>    const usecaseTest = () =>
should have a test for this scenario.

In an ideal world, for every conditional you put in your code, you should have a test that positively tests that conditional and another that negatively tests that conditional.

So please add a test that validates and/or invalidates this "if(route.entity)"

2022-08-16 15:07 UTC, jhomarolo commented
@mtperesvx could you please fix the conflict?

2022-08-20 18:20 UTC, mtperesvx commented
@jhomarolo Sure,
This branch was out of date. I opened another PR to upload the changes and closed this PR.

https://github.com/herbsjs/herbs2rest/pull/38

2022-08-20 18:20 UTC, closed without merging